added elastic pooling to SQL server
Energinet-DataHub/geh-shared-resources pull request #190
Opened 2022-04-25 10:22 UTC by Renetnielsen

## Description

## References

* #0000

2022-04-29 09:07 UTC, djorgensendk requested changes

2022-04-29 09:07 UTC, djorgensendk commented on build/infrastructure/main/mssql-data.tf
> +    capacity  = 4
In the TF module capacity is of type string. Should it be number instead?

2022-04-29 09:07 UTC, djorgensendk commented on build/infrastructure/main/mssql-data.tf
> +  source                        = "git::https://github.com/Energinet-DataHub/geh-terraform-modules.git//azure/mssql-server?ref=renetnielsen/elastic-pooling"
Must be changed before merge

2022-04-29 09:13 UTC, Renetnielsen commented on build/infrastructure/main/mssql-data.tf
> +    capacity  = 4
Fixed

2022-04-29 09:14 UTC, Renetnielsen commented on build/infrastructure/main/mssql-data.tf
> +  source                        = "git::https://github.com/Energinet-DataHub/geh-terraform-modules.git//azure/mssql-server?ref=renetnielsen/elastic-pooling"
Yup, can't change it before i can release the module. 
Which is when we have the backup strategy (or in conjunction with our VNET rollout)

2022-05-15 11:54 UTC, Renetnielsen commented
@cla-bot check

2022-08-25 09:16 UTC, kerbou commented
Closing PR, it's 6 months old

2022-08-25 09:16 UTC, closed without merging