Servicebus IAM: Create integrationevents topic
Energinet-DataHub/geh-shared-resources pull request #241
Opened 2022-08-23 11:53 UTC by kerbou

Enable Servicebus IAM
Create Integrationevents topic

Reference: https://github.com/Energinet-DataHub/the-outlaws/issues/444

2022-08-25 12:00 UTC, djorgensendk commented on build/infrastructure/main/sbt-charge-created.tf
> +  namespace_id        = module.sb_domain_relay.id
```suggestion
  namespace_id        = module.sb_domain_relay.id
```

2022-08-25 12:00 UTC, djorgensendk commented on build/infrastructure/main/sbt-domainrelay-integrationevent-received.tf
> +  ]
this subscription should be removed - each domain will have their own subscription with a filter applied

2022-08-25 12:14 UTC, djorgensendk commented
We will wait to merge this PR until version 8.0.0 of the Terraform modules are available

2022-08-26 11:23 UTC, djorgensendk requested changes

2022-08-26 11:23 UTC, djorgensendk commented on build/infrastructure/main/locals.tf
> +  sbt_integrationevent_received_topicname = "sbt-datahub-integrationevent-received"
This local can be deleted, and instead replaced by module.sbt_domainrelay_integrationevent_received.name where it is used.

2022-08-26 11:25 UTC, djorgensendk requested changes

2022-08-26 11:25 UTC, djorgensendk commented on build/infrastructure/main/sbt-domainrelay-integrationevent-received.tf
> +  project_name        = var.project_name
Should be var.domain_name_short instead, see e.g. mssql-data.tf line 22
```suggestion
  project_name        = var.domain_name_short
```

2022-08-26 11:30 UTC, kerbou commented on build/infrastructure/main/locals.tf
> +  sbt_integrationevent_received_topicname = "sbt-datahub-integrationevent-received"
I tried that yesterday, unsuccesfully - the property reference isn't calculated, it takes the value in the module as-is and TF then fails applying, because it tries to apply forwarding to a topic that doesn't exist

2022-08-26 11:38 UTC, djorgensendk commented on build/infrastructure/main/locals.tf
> +  sbt_integrationevent_received_topicname = "sbt-datahub-integrationevent-received"
in that case, the following must be added to the topic modules:
depends_on  = [
    module.sbt_domainrelay_integrationevent_received
  ]

Though I'm surprised it is necessary

2022-08-26 11:48 UTC, djorgensendk approved these changes

2022-08-26 11:51 UTC, merged